baseURL = "https://amy10001.github.io/blog/"
languageCode = "en-us"
title = "Amelia's Blog"
theme = "minos"

[params]
  author = "Amelia"
  description = "The hours."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/amy10001"

